version: '3.3'
services:
  myapp:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_ENV: ${APP_ENV}
    image: harbor190.iteam-dress.com/suppliychain/myapp:${BUILD_ID}
    container_name: myapp
    ports:
      - 81:80
      - 8081:8080
    restart: always
    extra_hosts:
      - "apiscm.xiaotest.como:10.1.3.133"
