# gitlab-redis
## 基于华为云sas云存储的StorageClass配置
#---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: cce-evs-redis
#   namespace: gitlab
#   annotations:
#     everest.io/disk-volume-type: SAS
#   labels:
#     failure-domain.beta.kubernetes.io/region: cn-east-3
#     failure-domain.beta.kubernetes.io/zone: cn-east-3a
# spec:
#   accessModes:
#   - ReadWriteOnce
#   resources:
#     requests:
#       storage: 10Gi
#   storageClassName: csi-disk

## 基于NFS共享存储
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-redis-claim
  namespace: gitlab
  annotations:
    volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
kind: Service
apiVersion: v1
metadata:
  name: gitlab-redis
  namespace: gitlab
  labels:
    app: gitlab-redis
spec:
  type: ClusterIP
  ports:
    - name: redis
      protocol: TCP
      port: 6379
      targetPort: 6379
  selector:
    app: gitlab-redis
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: gitlab-redis
  namespace: gitlab
  labels:
    app: gitlab-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitlab-redis
  template:
    metadata:
      name: gitlab-redis
      labels:
        app: gitlab-redis
    spec:
      containers:
      - name: gitlab-redis
        image: 'redis:5.0.9'
        imagePullPolicy: IfNotPresent
        args:
        - --loglevel warning
        ports:
        - name: redis
          containerPort: 6379
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 200m
            memory: 1Gi
        livenessProbe:
          exec:
            command:
              - redis-cli
              - ping
          initialDelaySeconds: 5
          timeoutSeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
              - redis-cli
              - ping
          initialDelaySeconds: 5
          timeoutSeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        volumeMounts:
          - name: data
            mountPath: /var/lib/redis
## 基于华为云sas云存储的StorageClass配置
#      volumes:
#      - name: data
#        persistentVolumeClaim:
#          claimName: cce-evs-redis
## 基于NFS共享存储
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: nfs-redis-claim
