apiVersion: v1
kind: Secret
metadata:
  name: gitlab
  namespace: gitlab
data:
  # 加密：echo -n 'P@ssw0rd' | base64
  # 解密：echo -n 'UEBzc3cwcmQ=' | base64 -d && echo
  db_pass: UEBzc3cwcmQ=
  db_user: Z2l0bGFi     # gitlab
  gitlab_root_pass: UEBzc3cwcmQ=
  gitlab_secrets_db_key_base: bE92U1NTcHMwSDJVU2tBTS9VajhZVUZMRjhPS25xUGhwTG5ocG41N0drTQ==
  gitlab_secrets_otp_key_base: aVZ6Z01OUFoybjFKRk1US1ltUUVUS3lYL3VpbWpKaDBMeVhFemlmTmhVNA==
  gitlab_secrets_secret_key_base: VFVFNWk3SW1wT0lQSzN6cnZCTnFUU09UWjI3ZjRkTm56cVNXejF6eW5BWQ==
type: Opaque
