# gitlab
---
## PVC
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-gitlab-claim
  namespace: gitlab
  annotations:
    volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
## Service
kind: Service
apiVersion: v1
metadata:
  name: gitlab
  namespace: gitlab
  labels:
    app: gitlab
## 华为云SLB配置
#  annotations:
#    # 提示：请根据实际可用的ELB信息修改如下三个注解信息的值；
#    kubernetes.io/elb.class: union
#    kubernetes.io/elb.id: a27c8dfa-a0b1-4f70-8453-6d997b2959ba
#    kubernetes.io/elb.mark: '0'
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80 
      targetPort: 80
      nodePort: 31080
    - name: ssh
      protocol: TCP
      port: 22
      targetPort: 22
      nodePort: 31022
  selector:
    app: gitlab
  type: NodePort
## 华为云SLB配置
#  type: LoadBalancer
#  # 请根据ELB上绑定的实际可用EIP修改如下属性值；
#  loadBalancerIP: 122.9.71.123
#  externalTrafficPolicy: Cluster
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: gitlab
  namespace: gitlab
  labels:
    app: gitlab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitlab
  template:
    metadata:
      name: gitlab
      labels:
        app: gitlab
    spec:
      containers:
      - name: gitlab
        image: 'sameersbn/gitlab:13.10.3'
        imagePullPolicy: IfNotPresent
        ports:
        - name: ssh
          containerPort: 22
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        env:
        - name: DB_ADAPTER
          value: 'postgresql'
        - name: DB_HOST
          value: gitlab-postgresql
        - name: DB_PORT
          value: '5432'
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: gitlab
              key: db_user
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: gitlab
              key: db_pass
        - name: DB_NAME
          value: gitlabhq_production
        - name: REDIS_HOST
          value: gitlab-redis
        - name: REDIS_PORT   
          value: '6379'
        - name: TZ
          value: 'Asia/Kolkata'
        - name: GITLAB_TIMEZONE
          value: 'Kolkata'
        - name: GITLAB_HTTPS
          value: 'false'
        - name: SSL_SELF_SIGNED
          value: 'false'
        - name: GITLAB_HOST           
          value: 'localhost'
        - name: GITLAB_PORT        
          value: '80' 
        - name: GITLAB_SSH_PORT   
          value: '22'
        - name: GITLAB_SECRETS_OTP_KEY_BASE
          # Be used to encrypt 2FA secrets in the database. "long-and-random-alpha-numeric-string"
          valueFrom:
            secretKeyRef:
              name: gitlab
              key: gitlab_secrets_otp_key_base
        - name: GITLAB_SECRETS_DB_KEY_BASE
          # Be used to encrypt CI secret variables, as well as import credentials, in the database.
          valueFrom:
            secretKeyRef:
              name: gitlab
              key: gitlab_secrets_db_key_base
        - name: GITLAB_SECRETS_SECRET_KEY_BASE
          # Be used for password reset links, and other 'standard' auth features.
          valueFrom:
            secretKeyRef:
              name: gitlab
              key: gitlab_secrets_secret_key_base
        - name: GITLAB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: gitlab
              key: gitlab_root_pass
        - name: GITLAB_ROOT_EMAIL 
          value: xiaotest@example.com
        resources: 
          requests:
            cpu: 1
            memory: 1Gi
          limits:
            cpu: 2
            memory: 8Gi
        livenessProbe:
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 300
          timeoutSeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
#        readinessProbe:
#          httpGet:
#            path: /
#            port: 80
#            scheme: HTTP
#          initialDelaySeconds: 30
#          timeoutSeconds: 30
#          periodSeconds: 10
#          successThreshold: 1
#          failureThreshold: 3
        volumeMounts:
        - name: data
          mountPath: /home/git/data
        - name: localtime
          mountPath: /etc/localtime
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: nfs-gitlab-claim
      - name: localtime
        hostPath:
          path: /etc/localtime
