apiVersion: v1
kind: PersistentVolume
metadata:
  name: rbd-demo-1
spec:
  accessModes:
   - ReadWriteOnce
  capacity:
    storage: 1G
  rbd:
    monitors:
    - '10.100.1.11:6789'
    - '10.100.1.12:6789'
    - '10.100.1.13:6789'
    pool: kubernetes
    image: demo-1.img 
    fsType: ext4
    user: kubernetes
    secretRef:
      name: ceph-secret
  persistentVolumeReclaimPolicy: Delete
  storageClassName: rbd
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rbd-demo-2
spec:
  accessModes:
   - ReadWriteMany
  capacity:
    storage: 1G
  rbd:
    monitors:
    - '10.100.1.11:6789'
    - '10.100.1.12:6789'
    - '10.100.1.13:6789'
    pool: kubernetes
    image: demo-2.img
    fsType: ext4
    user: kubernetes
    secretRef:
      name: ceph-secret
  persistentVolumeReclaimPolicy: Retain
  storageClassName: rbd
