apiVersion: v1
kind: Pod
metadata:
  name: test-pd
spec:
  containers:
  - image: harbor.xiaotest.com/library/myapp:v1
    name: test-container
    volumeMounts:
    - mountPath: /test-pd
      name: test-volume
  volumes:
  - name: test-volume
    hostPath:
      # directory location on host
      path: /data1
      # this field is optional
      # type: Directory
      type: FileOrCreate
