pipeline{
    agent {
        kubernetes {
            label 'kubectl'
        }
    }
    stages {
        stage('Source') {
            steps {
                git branch: 'develop', url: 'http://gitlab.gitlab.svc.cluster.local/root/spring-boot-helloworld-deployment.git'
            }
        }
        stage('Deploy') {
            steps {
                container('kubectl') {
                    withKubeConfig([credentialsId: 'k8s-cluser-admin-kubeconfig']) {
                        sh 'kubectl apply -f kubernetes/'
                    }
                }
            }
        }
    }
}
