---
apiVersion: v1
kind: ConfigMap
data:
  config.json: |-
    [
      {
        "clusterID": "00457924-1bcb-4c1e-8eb4-ce0a40e41826",
        "monitors": [
          "10.100.1.11:6789",
          "10.100.1.12:6789",
          "10.100.1.13:6789"
        ]
      }
    ]
metadata:
  name: ceph-csi-config
