---
apiVersion: v1
kind: Secret
metadata:
  name: csi-rbd-secret
  namespace: default
stringData:             # stringData 不需要使用 Base64 加密
  userID: admin
  userKey: AQAYX8dgyIM8CxAAesaNkOB6xxD0R6zzggoK6w==
