version: '3.3'
services:
  nginx:
    container_name: nginx
    image: harbor190.iteam-dress.com/base/nginx:1.19.7
    restart: always
    ports:
      - 80:80
      - 8080:8080
    links:
      - php-fpm-1:php-fpm-1
      - php-fpm-2:php-fpm-2
      - redis:redis
      - mysql:mysql
    working_dir: /etc/nginx/
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf/server.conf:/etc/nginx/conf.d/server.conf
      - ./nginx/conf/upstream.php.conf:/etc/nginx/conf.d/upstream.php.conf
      - ./nginx/log/:/var/log/nginx/
      - /data/www-data/:/data/www-data/
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 1G
  php-fpm-1:
    container_name: php-fpm-1
    image: harbor190.iteam-dress.com/base/php-fpm:7.3
    restart: always
#    ports:
#      - 9000:9000
    working_dir: /usr/local/etc/
    volumes:
      - /data/www-data/:/data/www-data/
      - ./php/conf/php.ini:/usr/local/etc/php/php.ini
      - ./php/conf/php-fpm.d/:/usr/local/etc/php-fpm.d/
      - ./php/log/php-fpm-1:/usr/local/log/
  php-fpm-2:
    container_name: php-fpm-2
    image: harbor190.iteam-dress.com/base/php-fpm:7.3
    restart: always
#    ports:
#      - 9000:9000
    working_dir: /usr/local/etc/
    volumes:
      - /data/www-data/:/data/www-data/
      - ./php/conf/php.ini:/usr/local/etc/php/php.ini
      - ./php/conf/php-fpm.d/:/usr/local/etc/php-fpm.d/
      - ./php/log/php-fpm-2/:/usr/local/log/
  redis:
    container_name: redis
    image: harbor190.iteam-dress.com/base/redis:5.0.8
    restart: always
#    ports:
#      - 6380:6380
    working_dir: /etc/redis
    volumes:
      - ./redis/conf/redis.conf:/etc/redis/redis.conf
      - ./redis/data:/data
    command: ["redis-server", "/etc/redis/redis.conf"]
  mysql:
    container_name: mysql
    image: harbor190.iteam-dress.com/base/mysql:5.7.32
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=''
      - MYSQL_DATABASE=''
      - MYSQL_USER=''
      - MYSQL_PASSWORD=''
    working_dir: /etc/mysql/conf.d
    volumes:
      - ./mysql/conf/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql/data:/var/lib/mysql
      - ./mysql/log:/var/log/mysql
networks:
  default:
    external:
      name: my-net
