apiVersion: v1
kind: Pod
metadata:
  name: file-test-pod
spec:
  containers:
  - name: test-container
    image: harbor.xiaotest.com/library/myapp:v1
    command: [ "/bin/sh", "-c", "ls /etc/config/; cat /etc/config/special.how" ]
    volumeMounts:
    - name: config-volume
      mountPath: /etc/config
  volumes:
  - name: config-volume
    configMap:
      name: special-config
  restartPolicy: Never
