apiVersion: v1
kind: Pod
metadata:
  name: rbd2
spec:
  containers:
    - image: nginx
      imagePullPolicy: IfNotPresent
      name: rbd-rw
      ports:
      - name: http
        containerPort: 80
      volumeMounts:
      - name: rbdpd
        mountPath: /data
  volumes:
    - name: rbdpd
      rbd:
        monitors:
        - '10.100.1.11:6789'
        - '10.100.1.12:6789'
        - '10.100.1.13:6789'
        pool: kubernetes
        image: rbd.img
        fsType: ext4
        # readOnly: true
        user: kubernetes
        secretRef:
          name: ceph-secret
